#!/usr/bin/env python3
"""Generate project-docs/incidents/INDEX.md (L1) for ANY project.

Tiered incident memory:
  L1 = INDEX.md (this output) — one line per incident, grouped by service/subsystem. Read FIRST.
  L2 = individual incident .md (full RCA, ~7KB). Read only the ones matched in L1.
  L3 = source code at file:line cited inside the RCA.

Project-agnostic: groups by the `**Service**` frontmatter field every incident already
carries (no hardcoded per-project keywords). Falls back to filename stem if Service absent.

Usage:
    python3 gen_incident_index.py [PROJECT_DIR]
PROJECT_DIR defaults to cwd. Looks for <PROJECT_DIR>/project-docs/incidents/*.md.
Run after writing/updating any incident.
"""
import os
import re
import sys
import glob


def parse(path):
    txt = open(path, encoding="utf-8", errors="replace").read()
    name = os.path.basename(path)
    title = name
    m = re.search(r"^#\s*Incident:\s*(.+)$", txt, re.M)
    if m:
        title = m.group(1).strip()
    date = (re.search(r"\*\*Date\*\*:\s*([0-9-]+)", txt) or [None, "????-??-??"])[1]
    sev = (re.search(r"\*\*Severity\*\*:\s*([A-Za-z]+)", txt) or [None, "?"])[1].lower()
    svc_full = (re.search(r"\*\*Service\*\*:\s*([^\*\n]+?)(?:\s{2,}|\n|$)", txt) or [None, ""])[1].strip()
    status = (re.search(r"\*\*Status\*\*:\s*([^\n]+)", txt) or [None, "?"])[1].strip()
    # base service for grouping: take first service before any "(" or "," and strip,
    # so "sync-service (source_mirror puller)" and "sync-service, report-service" both -> "sync-service"
    svc = re.split(r"[,(+/]", svc_full)[0].strip() if svc_full else ""
    if not svc or svc == "?":
        # fallback: filename stem after the date prefix
        stem = re.sub(r"^\d{4}-\d{2}-\d{2}-", "", name).rsplit(".md", 1)[0]
        svc = stem.split("-")[0] or "other"
    closed = bool(re.search(r"\b(FIXED|ARCHIVED|RESOLVED)\b", status, re.I))
    return dict(name=name, title=title, date=date, sev=sev, svc=svc, svc_full=svc_full, status=status, closed=closed)


def main():
    proj = sys.argv[1] if len(sys.argv) > 1 else os.getcwd()
    inc_dir = os.path.join(proj, "project-docs", "incidents")
    if not os.path.isdir(inc_dir):
        print(f"no incidents dir: {inc_dir}", file=sys.stderr)
        sys.exit(1)

    files = sorted(glob.glob(os.path.join(inc_dir, "*.md")))
    rows = [parse(f) for f in files if os.path.basename(f) != "INDEX.md"]
    if not rows:
        print(f"no incidents found in {inc_dir}", file=sys.stderr)
        sys.exit(0)

    open_rows = [r for r in rows if not r["closed"]]
    closed_rows = [r for r in rows if r["closed"]]

    out = []
    out.append("# Incident Index (L1) — READ THIS FIRST before investigating\n")
    out.append(f"_{len(rows)} incidents — {len(open_rows)} OPEN, {len(closed_rows)} closed. "
               "Auto-generated by `gen_incident_index.py` — do not edit by hand._\n")
    out.append("Flow: scan OPEN first → open matching incident `.md` (L2, full RCA) → drill to "
               "code (L3, file:line in the RCA). Never read every file. CLOSED = already fixed/archived "
               "(history only — don't re-investigate).\n")
    out.append("Regenerate after writing/closing an incident: "
               "`python3 ~/globalclaude/scripts/gen_incident_index.py <project-dir>`\n")

    def emit(rows_subset):
        groups = {}
        for r in rows_subset:
            groups.setdefault(r["svc"], []).append(r)
        for svc in sorted(groups, key=lambda s: (-len(groups[s]), s)):
            rs = sorted(groups[svc], key=lambda r: r["date"], reverse=True)
            out.append(f"\n### {svc} ({len(rs)})\n")
            for r in rs:
                detail = f"{r['svc_full']}; {r['status']}" if r.get('svc_full') and r['svc_full'] != r['svc'] else r['status']
                out.append(f"- `{r['sev']}` {r['date']} — **{r['title']}** _({detail})_ → `{r['name']}`")

    out.append("\n# OPEN\n")
    if open_rows:
        emit(open_rows)
    else:
        out.append("\n_(none open)_\n")
    if closed_rows:
        out.append("\n# CLOSED (fixed / archived — history)\n")
        emit(closed_rows)

    open(os.path.join(inc_dir, "INDEX.md"), "w", encoding="utf-8").write("\n".join(out) + "\n")
    print(f"INDEX.md written: {len(rows)} incidents ({len(open_rows)} open, {len(closed_rows)} closed) → {inc_dir}/INDEX.md")


if __name__ == "__main__":
    main()
